User.create!(name: '斎藤', age: 34)
User.create!(name: '小島', age: 23)
User.create!(name: '後藤', age: 30)
User.create!(name: '小林', age: 34)
User.create!(name: 'した林', age: 34)
User.create!(name: '藤田', age: 239)
